name       : containerd
version    : 1.0.0_beta3
release    : 9
source     :
    - git|https://github.com/containerd/containerd.git :  v1.0.0-beta.3
license    : Apache-2.0
component  : virt
summary    : A daemon to control OCI container runtimes
description: |
    A daemon to control OCI container runtimes
builddeps  :
    - btrfs-progs-devel
    - golang
build      : |
    mkdir -p src/github.com/containerd
    ln -s `pwd` src/github.com/containerd/containerd
    export GOPATH="`pwd`"
    pushd src/github.com/containerd/containerd
    %make LDFLAGS=
install    : |
    install -D -d -m 00755 $installdir/usr/bin
    install -m 00755 bin/containerd $installdir/usr/bin/containerd
    install -m 00755 bin/ctr $installdir/usr/bin/ctr
    install -m 00755 bin/containerd-shim $installdir/usr/bin/containerd-shim
