name       : containerd
version    : 1.1.3
release    : 11
source     :
    - git|https://github.com/containerd/containerd.git : v1.1.3
license    : Apache-2.0
component  : virt
summary    : A daemon to control OCI container runtimes
description: |
    A daemon to control OCI container runtimes
builddeps  :
    - pkgconfig(libseccomp)
    - btrfs-progs-devel
    - golang
build      : |
    mkdir -p src/github.com/containerd
    ln -s `pwd` src/github.com/containerd/containerd
    export GOPATH="`pwd`"
    pushd src/github.com/containerd/containerd
    %make LDFLAGS=
install    : |
    install -D -d -m 00755 $installdir/usr/bin
    install -m 00755 bin/containerd $installdir/usr/bin/containerd
    install -m 00755 bin/containerd-release $installdir/usr/bin/containerd-release
    install -m 00755 bin/containerd-shim $installdir/usr/bin/containerd-shim
    install -m 00755 bin/containerd-stress $installdir/usr/bin/containerd-stress
    install -m 00755 bin/ctr $installdir/usr/bin/ctr
