name       : containerd
version    : 0.2.5
release    : 5
source     :
    - git|https://github.com/docker/containerd.git : v0.2.5
license    : Apache-2.0
component  : virt
summary    : A daemon to control OCI container runtimes
description: |
    A daemon to control OCI container runtimes
builddeps  :
    - golang
build      : |
    mkdir -p src/github.com/docker
    ln -s `pwd` src/github.com/docker/containerd
    export GOPATH="`pwd`:%libdir%/golang"
    pushd src/github.com/docker/containerd
    %make LDFLAGS=
install    : |
    install -D -d -m 00755 $installdir/usr/bin
    install -m 00755 bin/containerd $installdir/usr/bin/containerd
    install -m 00755 bin/ctr $installdir/usr/bin/ctr
    install -m 00755 bin/containerd-shim $installdir/usr/bin/containerd-shim
