name       : containerd
version    : 1.4.6
release    : 27
source     :
    - git|https://github.com/containerd/containerd.git : v1.4.6
license    : Apache-2.0
component  : virt
summary    : A daemon to control OCI container runtimes
description: |
    A daemon to control OCI container runtimes
builddeps  :
    - btrfs-progs-devel
    - golang
environment: |
    export GO111MODULE=auto
    export GOPATH="${workdir}"
build      : |
    mkdir -p src/github.com/containerd
    ln -s `pwd` src/github.com/containerd/containerd
    pushd src/github.com/containerd/containerd
    %make LDFLAGS=
install    : |
    install -Ddm00755 $installdir/usr/bin
    install -m00755 bin/containerd $installdir/usr/bin/containerd
    install -m00755 bin/containerd-shim $installdir/usr/bin/containerd-shim
    install -m00755 bin/containerd-shim-runc-v2 $installdir/usr/bin/containerd-shim-runc-v2
    install -m00755 bin/containerd-stress $installdir/usr/bin/containerd-stress
    install -m00755 bin/ctr $installdir/usr/bin/ctr
