name       : containerd
version    : 0.2.2
release    : 2
source     :
    - https://github.com/docker/containerd/archive/v0.2.2.tar.gz : a21efc7ea4bb97306ae9807caadca6782358679f38d3afd606cb599b6853bc52
license    : Apache-2.0
component  : virt
summary    : A daemon to control OCI container runtimes
description: |
    A daemon to control OCI container runtimes
builddeps  :
    - golang
build      : |
    mkdir -p src/github.com/docker
    ln -s `pwd` src/github.com/docker/containerd
    export GOPATH="`pwd`:%libdir%/golang"
    %make LDFLAGS=
install    : |
    install -D -d -m 00755 $installdir/usr/bin
    install -m 00755 bin/containerd $installdir/usr/bin/containerd
    install -m 00755 bin/ctr $installdir/usr/bin/ctr
    install -m 00755 bin/containerd-shim $installdir/usr/bin/containerd-shim
